version: '3'
services:
  portainer:
    image: portainer/agent:latest
    container_name: portainer_agent
    ports:
      - '${PORTAINER_AGENT_PORT:-9001}:9001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_agent_data:/data
    restart: always

volumes:
  portainer_agent_data:
